### ISSUE TITLE
手机端插件商店列表显示问题

### ISSUE THREAD

**Issue by Dk2048** [chekun/AppStore#13]
插件名重叠严重
<a href='http://i.imgur.com/kgnQn9Q' title=''><img src='http://i.imgur.com/kgnQn9Q.jpg' alt='' title='Hosted by imgur.com' /></a>
还有一个问题，安装商店插件的时候需要把商店插件的文件夹名称改成Appstore，如果是默认的Appstore-版本号 就会出现404报错，这点应该在说明里加上吧

**Comment by Dk2048** [comment]
不知道那个图片你能不能看到，再发一次链接吧
http://i.imgur.com/kgnQn9Q.jpg

**Comment by chekun** [comment]
1. 暂时没针对做响应式布局
2. Readme中有说明插件家的文件夹叫AppStore

![qq20150311-1 2x](https://cloud.githubusercontent.com/assets/1967804/6589435/e349b3b4-c7da-11e4-9ed6-e62e2a048ed7.png)
