### ISSUE TITLE
提示没有写入权限

### ISSUE THREAD

**Issue by xau0at** [chekun/AppStore#17]
应用商店中下载应用提示没有写入权限

**Comment by chekun** [comment]
插件的目录给写权限即可。

**Comment by xau0at** [comment]
依然不行

**Comment by chekun** [comment]
@xau0at 具体说下你代码的运行环境

**Comment by xau0at** [comment]
@chekun  用的lnmp 一键安装包 然后装的typecho 给过目录权限后还是不行

**Comment by chekun** [comment]
@xau0at windows吧？给everyone所有权限并递归到子目录。

**Comment by chekun** [comment]
关闭。

**Comment by xau0at** [comment]
@chekun  centos系统 777权限 递归到子文件夹 依然提示没有权限
