### ISSUE TITLE
Typecho 0.9 + Lighttpd +php5.4  路由失败，商店页面404

### ISSUE THREAD

**Issue by orzzz** [chekun/AppStore#19]
如上所述，已经开启重写，不知是否是Lighttpd的重写规则不适应商店

**Comment by chekun** [comment]
是否将本插件目录命名为AppStore了哈？

**Comment by orzzz** [comment]
是的，已经重命名为AppStore，并且chown到web用户，今天环境换到linux+Apache2+php5+sqlite3也是这样，无法启用

**Comment by chekun** [comment]
@orzzz 有木有我可以访问的地址哈？

**Comment by orzzz** [comment]
你需要一个什么地址？现在还没有上线，只在本地开发的

**Comment by chekun** [comment]
@orzzz 这样的话，你可以自己查查日志，或者断点看一下，究竟请求到了哪里 :smile:
