### ISSUE TITLE
没有找到任何插件: The missing plugins' store for Typecho 

### ISSUE THREAD

**Issue by note4** [chekun/AppStore#20]
应用商店 The missing plugins' store for Typecho  

没有找到任何插件

**Comment by chekun** [comment]
插件数据是从这个地址获得的 http://typecho.chekun.me/packages.json 里面是有数据的。

**Comment by chekun** [comment]
@note4 在插件设置中，把服务器地址换成 https://typecho.chekun.me/packages.json 应该就好了。

**Comment by YinHeng89** [comment]
为什么我的替换了也没用  是不是我 版本 1.1 (17.8.17) 版本高了？

**Comment by chekun** [comment]
@YinHeng89 新发布的版本吧，我来复现一下

**Comment by chekun** [comment]
@YinHeng89 亲测没有问题。

**Comment by YinHeng89** [comment]
@chekun 额 不好意思打扰了！这个问题还是没能解决  服务器环境是 万网的虚拟主机！不管换任何版本还是服务器地址或者获取方式 ，都不能显示出商店内容，你能帮忙看看吗
