### ISSUE TITLE
建议把已下载的对勾标志左移

### ISSUE THREAD

**Issue by ghost** [chekun/AppStore#23]
下载了的插件有一个对勾，对勾位置是挨着下一个插件的，总是看错，建议把对勾放到“下载”二字旁边，或者给已经下载的项目设置背景色用以区分。

---

商店里右上角建议链接-https://chekun.me/typecho-app-store.html -已坏。

**Comment by chekun** [comment]
谢谢提醒 👍 

方便的话可以直接修改发个PR 😃
