### ISSUE TITLE
没有找到任何插件

### ISSUE THREAD

**Issue by zhyt0520** [chekun/AppStore#29]
新安装的typecho，显示找不到插件，已安装的也不显示， 把地址换成 https://typecho.chekun.me/packages.json 不管用

请问我该如何检查问题？

![snipaste20170209_003126](https://cloud.githubusercontent.com/assets/10279099/22746566/1f9dba52-ee5f-11e6-9477-b427d11579fc.png)

**Comment by chekun** [comment]
建一个test.php文件，里面放

```
<?php
    $url = 'https://typecho.chekun.me/packages.json';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    $out = curl_exec($ch);
    curl_close($ch);
    var_dump(json_decode($out));
```

看看结果呢

**Comment by zhyt0520** [comment]
访问这个 test.php，输出的结果是 null 。。。

**Comment by chekun** [comment]
你可以把 php 报的报错打开看看，我怀疑你的PHP对https请求不支持。

**Comment by zhyt0520** [comment]
果然。。。不支持https
请问可以把插件设置成用http吗？
![snipaste20170210_170935](https://cloud.githubusercontent.com/assets/10279099/22820928/cb8874ce-efb3-11e6-93f8-19fcf9b816a8.png)

**Comment by chekun** [comment]
可以参照这个[地址](https://www.oschina.net/question/231885_163798?sort=time)修改下这里:https://github.com/chekun/AppStore/blob/master/helpers/helpers.php#L55

**Comment by zhyt0520** [comment]
失败了，还是用之前那个test.php
我在里面加了如下两行
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
结果还是返回 null
我在网上尝试搜索其他方法，也没找到

**Comment by chekun** [comment]
加上
```
CURLOPT_SSLVERSION => 0,
```
再试试看

**Comment by zhyt0520** [comment]
还是用curl_setopt吗？我这样试的，还是返回 NULL
```
<!-- test.php -->
<?php
    $url = 'https://typecho.chekun.me/packages.json';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_SSLVERSION, 0);
    $out = curl_exec($ch);
    curl_close($ch);
    var_dump(json_decode($out));
?>
```

**Comment by jzwalk** [comment]
你php版本多少？不会是不支持json_decode吧 - =

**Comment by zhyt0520** [comment]
php 是5.3，应该支持的吧，如果不支持应该报错，不能返回 NUll 啊

**Comment by zhyt0520** [comment]
用的万网的虚拟主机

**Comment by jzwalk** [comment]
我不懂curl。。是不是支持模块有什么奇葩问题 - -

**Comment by feiyu0** [comment]
同样的问题

我是sqlite，开发版的typecho


<?php
    $url = 'https://typecho.chekun.me/packages.json';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_SSLVERSION, 0);
    $out = curl_exec($ch);
    curl_close($ch);
    var_dump(json_decode($out));
?>

试了这段代码，有出现一大堆的名称，前面那段代码是null

**Comment by FaceChan** [comment]
旧版的curl如果没有配合ssl编译的话是不支持https访问的。可以通过phpinfo()函数查看curl
![curl](https://cloud.githubusercontent.com/assets/2556742/23163167/4a3e6a24-f86c-11e6-9618-dcb11e6704e6.png)

**Comment by chekun** [comment]
@FaceChan 正解

**Comment by feiyu0** [comment]
@chekun @FaceChan 
![121](https://cloud.githubusercontent.com/assets/4783742/23194241/f9206b48-f8e7-11e6-89aa-490a589f9e1a.png)

**Comment by feiyu0** [comment]
这样的不行的吗

**Comment by zhyt0520** [comment]
我的phpinfo里面，SSL的yes，Protocols的https，也都有

**Comment by chekun** [comment]
@feiyu0 @zhyt0520 

试试看 

```
var_dump(file_get_contents('https://typecho.chekun.me/packages.json'));
```

**Comment by FaceChan** [comment]
@zhyt0520 @feiyu0 你们可以参考下前面提到的代码，试下http有没有输出。如果有，那基本可以确认是因为curl编译没有选择ssl支持。
test.php
`<?php
    $url = 'http://www.xinhuanet.com/jrgz/20170222a/index.htm';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    $out = curl_exec($ch);
    curl_close($ch);
    var_dump($out);`
