### ISSUE TITLE
阿里云虚拟主机 没有找到任何插件

### ISSUE THREAD

**Issue by ywzhaiqi** [chekun/AppStore#36]
阿里云虚拟主机，通过 ftp 上传->安装->启用后，显示 `没有找到任何插件`。

研究了下，发现了是由于 `helpers/helpers.php` 文件中的 `http_get` 无效。（对php不熟悉，不知道原因，用 [Requests for PHP](https://github.com/rmccue/Requests) 正常）

临时解决方法，修改 `http_get` 函数为：

```php
function http_get($url)
{
    return file_get_contents($url);
}
```

**Comment by FaceChan** [comment]
请确认php环境已提供curl支持.

**Comment by ywzhaiqi** [comment]
测试结果是

    Curl error: SSL connect error

**Comment by chekun** [comment]
@ywzhaiqi 请使用最新版 https://github.com/chekun/AppStore/releases/tag/v2.0.0
