### ISSUE TITLE
1.0 (14.10.10)版 点击启用掉转到空白页面是什么问题呢？

### ISSUE THREAD

**Issue by yanwen** [chekun/AppStore#37]
NGINX的服务器。装其他app是没问题的。装这个之后 点启用会跳转到空白页面。不能安装

**Comment by chekun** [comment]
应该是报错了，你看一下`nginx`的`error`日志

**Comment by binyuj** [comment]
php版本问题吧，我的php5.3也是这样，https://github.com/chekun/AppStore/blob/master/Plugin.php#L90
这个语法不支持，改回array就可以了

**Comment by chekun** [comment]
没错，如@binyuj 所说，这个需要 php `5.4+`

**Comment by yanwen** [comment]
typecho 支持5.3+的 这个支持5.4+的话 貌似有点难搞了.. 能改一下兼容 5.3么??

**Comment by chekun** [comment]
@yanwen 可以的，暂时你可以先自行修改一下 https://github.com/chekun/AppStore/blob/master/Plugin.php#L90  这里，改为下面的皆可

```
array('curl' => 'curl', 'file_get_contents' => 'file_get_contents'),
```

回头我空了，我来改代码后发布新版本。

**Comment by yanwen** [comment]
@chekun 感谢
