### ISSUE TITLE
请问下应用商店对服务器有没有什么要求呢？

### ISSUE THREAD

**Issue by YinHeng89** [chekun/AppStore#38]
![tim 20170822163244](https://user-images.githubusercontent.com/22227621/29556198-a4b04a0c-8757-11e7-8e26-33f77ec9b21b.jpg)
我这边使用万网的虚拟主机！不管怎么调试 都不能正常显示商店内容

**Comment by chekun** [comment]
没什么特殊的要求吧,要说要求，一下2点

- PHP支持SSL请求
- PHP >= 5.4

**Comment by YinHeng89** [comment]
@chekun  恩 最后一个问题 万网的虚拟主机 不支持ssl请求的话  直接把链接改成http就行了吗？还是需要其他办法呢？

**Comment by chekun** [comment]
@YinHeng89 服务器强行使用了https，http的请求也会被重定向到https，一般服务器都是支持https的吧，万网虚拟主机这么坑？

**Comment by YinHeng89** [comment]
@chekun 那应该没办法解决了，万网的虚拟主机貌似都不支持ssl请求！我再想想其他办法！谢谢了！

> 云虚拟主机(包括共享，独享，轻云)不支持SSL，OpenSSL，HTTPS。
