### ISSUE TITLE
无法安装插件，报错没有写入权限

### ISSUE THREAD

**Issue by yidafu** [chekun/AppStore#40]
### 报错权限不够

![](http://image.yidaqiang.cn/blog/cant-write.png)

**跪求解决方案**

**我想开自动挡，不要手动挡。**

**Comment by chekun** [comment]
php运行在哪个用户下？把项目目录的所有者改为那个用户，如php运行在service用户下，项目目录为/data/typecho,那么执行
```
chown service:service -R /data/typecho
```

**Comment by yidafu** [comment]
嗯嗯，解决了。下午升级了一下typecho没注意到是Root用户操作。谢谢！
