### ISSUE TITLE
sae下无法创建.app_store目录，求兼容

### ISSUE THREAD

**Issue by jwcn** [chekun/AppStore#8]
sae下无法创建.app_store目录，求兼容

**Comment by fengyunljp** [comment]
@chekun 能不能尝试使用KVDB作为缓存啊，谢谢啦，非常希望支持SAE平台

**Comment by chekun** [comment]
@fengyunljp  你这个和这个主题无关哦。

**Comment by fengyunljp** [comment]
@chekun 奥奥可能我没有表达清楚。现在在SAE平台是无法激活这个插件的，抛出异常是无法创建目录。希望能够对于SAE/BE/JAE出一个特别的版本，哪怕只能使用部分功能，也是非常不错的。例如无法直接一键安装就直接显示出来插件下载地址，我们来手动上传到网站目录都可以。

**Comment by chekun** [comment]
@fengyunljp 这点是可以的，哈哈。

**Comment by chekun** [comment]
@fengyunljp 麻烦帮我测试下 develop里最新的代码，没有问题的话就发布1.2.0 。

**Comment by fengyunljp** [comment]
@chekun 恩，我这边测试没有问题
不过貌似有一个BUG在以前的版本中也有，列表的最后一个没有插件还是显示出来了一个框。。。

**Comment by chekun** [comment]
@fengyunljp 这个应该是有个插件没写注解导致的 不过我会在插件索引端解决

**Comment by chekun** [comment]
closed via #12
