### ISSUE TITLE
主题更新

### ISSUE THREAD

**Issue by liuronghuan** [chekun/AppStore#9]
很感谢您写出这么好的插件，我是一个网页爱好者，预发布一款自己的主题，希望能将您的插件集成在我的主题中，当主题有更新的时候，后台提示用户，并且可以实现一键更新，能否更出一个实例，谢谢！

**Comment by chekun** [comment]
目前这个只是插件的市场，不是主题的市场。 :smile:

**Comment by liuronghuan** [comment]
感谢您的回复，希望以后能开发出此类插件
